[auto_discover]
node_exporter_url = <node_exporter_url>
perfsonar_host_exporter_url = <perfsonar_host_exporter_url>
#In seconds - max 86400, min 3600
check_interval = 3600
#Set this off to only register the supplied records
allow_auto_discover = 1

# Contains the information to overwrite/ add if auto_discover is True
# Otherwise registers only the information found here
[record_data]
interface_overwite_conf_path = /etc/perfsonar/ls-config/ls-record-conf/interfaces.json
host_overwite_conf_path = /etc/perfsonar/ls-config/ls-record-conf/host.json

[server_config]
server = <sever>

#activehosts.json for adding API
