[auto_discover]
node_exporter_url = https://localhost/node_exporter/metrics
perfsonar_host_exporter_url = https://localhost/perfsonar_host_exporter
#In seconds - max 86400, min 3600
register_interval = 3600
# How often to check for changes in config file
check_interval = 3600
#Set this off to only register the supplied records
allow_auto_discover = 1

# Contains the information to overwrite/ add if auto_discover is True
# Otherwise registers only the information found here
[record_data]
interface_overwite_conf_path = /etc/perfsonar/pslookup/pslookup-record-conf/interfaces.json
host_overwite_conf_path = /etc/perfsonar/pslookup/pslookup-record-conf/host.json

[server_config]
server = http://ls.perfsonar.net:80

#activehosts.json for adding API
